# Generated by Django 4.2.7 on 2026-03-17 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "quantity_per_person",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity per person in grams/ml/units",
                        max_digits=8,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("grams", "Grams"),
                            ("ml", "Milliliters"),
                            ("units", "Units"),
                        ],
                        default="grams",
                        max_length=10,
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per gram/ml/unit",
                        max_digits=10,
                    ),
                ),
                (
                    "preparation_time",
                    models.PositiveIntegerField(
                        help_text="Preparation time in minutes"
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("all", "All Seasons"),
                            ("summer", "Summer"),
                            ("winter", "Winter"),
                            ("monsoon", "Monsoon"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dishes",
                        to="menu.category",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
    ]
