# Generated by Django 4.2.7 on 2026-03-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="budget_cap",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Personal budget cap for individual users",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dietary_preference",
            field=models.CharField(
                choices=[
                    ("all", "No Preference"),
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="service_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="Service charge % added on top of food cost",
                max_digits=5,
            ),
        ),
    ]
