# Generated by Django 4.2.7 on 2026-03-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="client_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="event",
            name="client_name",
            field=models.CharField(
                blank=True, help_text="Client name for organizers", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="client_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="event",
            name="confirmed_guests",
            field=models.PositiveIntegerField(
                blank=True, help_text="Confirmed RSVP count", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="markup_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Per-event markup override for caterers",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="personal_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Personal budget cap for this event",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="service_charge",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Per-event service charge override",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="buffer_percentage",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="eventmenu",
            name="quantity_per_person_override",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
