# Generated by Django 4.2.7 on 2026-03-18 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_venue_support"),
        ("events", "0002_event_client_email_event_client_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="venue_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked venue for venue-specific menu",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="menu.venue",
            ),
        ),
    ]
